### ISSUE TITLE
authorization is missing

### ISSUE THREAD

**Issue by ahmadod** [hashmode/cakephp-tinymce-elfinder#1]
Hello
Thanks for creating this plugin , the thing that missing is to implement some sort of authorization .
is there anyway to implement Cakedc users plugin  ??

**Comment by ahmadod** [comment]
i guess i have fixed the problem with adding this lines in my initialize method in appController
 $this->Auth->deny(['elfinder','connector']);

**Comment by hashmode** [comment]
Hi there, yes the authorization is not considered, it should be done as part of the application. But this is a good security point, I will add into readme. Thanks
